config/routes.rb
Rails.application.routes.draw do
  root to: "cocktails#home"
  resources :cocktails do
    resources :doses, only: :create
    resources :reviews, only: :create
  end

  resources :doses, only: :destroy
  resources :reviews, only: :destroy
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
    has_many :doses, dependent: :destroy
    has_many :reviews, dependent: :destroy
    has_many :ingredients, through: :doses
    validates :name, presence: true, uniqueness: { message: "This cocktail already exists" }
    has_one_attached :cocktail_image
    validates :cocktail_image, presence: { message: "You must add an image" }

    def self.search(search)
        if search
            doses = []
            cocktail_ids = []
            ingredients = Ingredient.where("name LIKE '%#{search.capitalize}%'")
            ingredients.each do |ingredient|
                doses << Dose.find_by(ingredient_id: ingredient.id)
            end
            doses.each do |dose|
                if dose
                    cocktail_ids << dose.cocktail_id
                end
            end
            result = Cocktail.where("name LIKE '%#{search.capitalize}%' OR id IN (?)", cocktail_ids)
            # raise
        else
            result = Cocktail.all
        end
    return result
    end
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :cocktail_id, uniqueness: { scope: :ingredient_id }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
    has_many :doses
    validates :name, presence: true, uniqueness: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :cocktail
  validates :rate, inclusion: { in: (1..5) }, presence: true
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
    before_action :find_cocktail, only: [:show, :edit, :update, :destroy]
    def index
        @cocktails = Cocktail.search(params[:query])
    end
    def show
        @dose = Dose.new
        @review = Review.new
    end
    def new
        @cocktail = Cocktail.new
    end
    def create
        @cocktail = Cocktail.new(params_cocktail)
        if @cocktail.save
            redirect_to cocktails_path
        else
            render :new
        end
    end
    def edit
    end
    def update
        if @cocktail.update(params_cocktail)
            redirect_to cocktail_path(@cocktail)
        else
            render :edit
        end
    end
    def destroy
        @cocktail.destroy
        redirect_to cocktails_path
    end

    private
    def params_cocktail
        params.require(:cocktail).permit(:name, :cocktail_image)
    end
    def find_cocktail
        @cocktail = Cocktail.find(params[:id])
    end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
    before_action :find_cocktail, only: [:new, :create]
    def create
        @dose = Dose.new(params_dose)
        @dose.cocktail = @cocktail
        # puts @dose.valid?
        # puts @dose.errors
        if @dose.save
            redirect_to cocktail_path(@cocktail)
        else
            @review = Review.new
            render 'cocktails/show'
        end
    end
    def destroy
        @dose = Dose.find(params[:id])
        @dose.destroy
        redirect_to cocktail_path(@dose.cocktail)
    end

    private
    def params_dose
        params.require(:dose).permit(:description, :ingredient_id)
    end
    def find_cocktail
        @cocktail = Cocktail.find(params[:cocktail_id])
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    def create
        @cocktail = Cocktail.find(params[:cocktail_id])
        @review = Review.new(params_dose)
        @review.cocktail = @cocktail
        if @review.save
            redirect_to cocktail_path(@cocktail)
        else
            @dose = Dose.new
            render 'cocktails/show'
        end

    end

    def params_dose
        params.require(:review).permit(:content, :rate)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def icon_search(name, size=1)
        #icon("camera-retro")
        #<i class="icon-camera-retro"></i> 
      
        html = "<i class='fas fa-#{name}' "
        html += "style='font-size:#{size}em' "
        html += "></i>"
        html.html_safe
      end

      def icon_trash(name, size=0.7)
        #icon("camera-retro")
        #<i class="icon-camera-retro"></i> 
      
        html = "<i class='fas fa-#{name}' "
        html += "style='font-size:#{size}em' "
        html += "></i>"
        html.html_safe
      end

      def icon_edit(name, size=0.7)
        #icon("camera-retro")
        #<i class="icon-camera-retro"></i> 
      
        html = "<i class='far fa-#{name}' "
        html += "style='font-size:#{size}em' "
        html += "></i>"
        html.html_safe
      end
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cocktails/_form.html.erb
<div class="container mt-2 col-4 offset-4">
    <% if action_name == "new" %>
        <h1>Add a new cocktail</h1>
    <% else %>
        <h1>Edit the cocktail cocktail</h1>
    <% end %>
    <%= simple_form_for @cocktail do |f| %>
    <div class="form-group">
        <%= f.label :name%>
        <%= f.text_field :name, class: "form-control"%>
    </div>
    <div class="form-group">
        <%= f.label :cocktail_image %>
        <%= f.file_field :cocktail_image %>
    </div>
        <% if action_name == "new" %>
            <%= f.submit "Add", class:"btn-yellow-full" %>
        <% else %>
            <%= f.submit "Edit", class:"btn-yellow-full" %>
        <% end %>
    <% end %>
</div>

app/views/cocktails/edit.html.erb
<%= render 'form', cocktail: @cocktail %>

app/views/cocktails/home.html.erb
<div class="homepage">
    <h1>Crazy Cocktails</h1>
    <%= link_to "See all the cocktails", cocktails_path, class:"btn-homepage" %>
    <div class="search-homepage">
        <%= form_tag cocktails_path, method: :get, class: "form-inline" do %>
            <%= text_field_tag :query, "", placeholder: "Search specific cocktails or ingredients...", class: "searchbar-homepage" %>
            <button class='btn-homepage-search ml-1' id="search-cocktails" style='width:40px;'>
                <%= icon_search("search") %>
            </button>
        <% end %>
    </div>
</div>

app/views/cocktails/index.html.erb
<div class="container">
    <div class="title-cocktails"><span style="color: #d8a649;">T</span>he <span style="color: #d8a649;">C</span>ocktails</div>
    <div class="row">
        <% @cocktails.each do |cocktail| %>
        <div class="col-4">
            <div class="card-cocktail my-2" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path cocktail.cocktail_image.key %>')">
                <div class="card-cocktail-name">
                    <%= cocktail.name %>
                    <p hidden><%= cocktail.id %></p>
                </div>
                <div class="cocktail-action">
                    <%= link_to icon_edit("edit"), edit_cocktail_path(cocktail), class: "mr-2"%>
                    <%= link_to icon_trash("trash"), cocktail_path(cocktail), method: :delete, data: { confirm: "Are you sure?"} %>
                </div>
            </div>
        </div>
        <% end %>
    </div>
</div>

app/views/cocktails/new.html.erb
<%= simple_form_for @cocktail do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.submit "Create" %>
<% end %>

app/views/cocktails/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path @cocktail.cocktail_image.key %>')">
<h1><%= @cocktail.name %></h1>
<div class="container">
  <div class="row container-banner">
    <div class="card-element col-6">
      <h2>Description</h2>
      <p>Apprenez à réaliser un cocktail <b><%= @cocktail.name %></b> en toute simplicité</p>
    </div>
    <div class="card-ingredient col-5 offset-1">
      <h3>Ingrédients</h3>
      <% @cocktail.doses.each do |dose| %>
        <div class="d-flex align-items-center">
            <div class="ingredient">
                <%= dose.ingredient.name %> -
            </div>
            <div class="dose ml-2">
                <%= dose.description %>
            </div>
            <div class="btn-remove-ingredient ml-2 mb-1">
                <%= link_to icon_trash("trash"), dose_path(dose), method: :delete, data: { confirm: "are you sure ?"} %></p>
            </div>
        </div>
      <% end %>
    </div>
      <div class="col-md-6 my-3 card-element">
          <h3>Review</h3>
          <div class="review">
          <% @cocktail.reviews.each do |review| %>
            <div class="d-flex">
              <% review.rate.times do |star| %>
                <%= "⭐" %>
              <% end %>
              - <%= review.content %>
            </div>
          <% end %>
          </div>
          <%= render 'reviews/form', cocktail: @cocktail %>
      </div>
      <div class="col-md-5 my-3 offset-1 card-element">
          <h3>Add a new dose</h3>
          <%= render 'doses/form', cocktail: @cocktail %>
      </div>
    </div>
  </div>
</div>

app/views/doses/_form.html.erb
<div class="container mt-2">
    <%= simple_form_for [@cocktail, @dose] do |f| %>
    <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= f.association :ingredient %>
    </div>
        <%= f.submit "Add a dose", class:"btn-yellow-full" %>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% unless action_name == "home" %>
      <%= render 'shared/navbar' %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/reviews/_form.html.erb
<div class="container mt-2">
    <%= simple_form_for [@cocktail, @review] do |f| %>
    <div class="form-group">
        <%= f.label :content %>
        <%= f.text_area :content, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= f.label :rate %>
        <%= f.number_field :rate %>
    </div>
        <%= f.submit "Add a review", class:"btn-yellow-full" %>
    <% end %>
</div>

app/views/reviews/new.html.erb
<%= render 'form' cocktail: @cocktail, review: @review %>

app/views/shared/_navbar.html.erb
<div class="navbar">
    <div class="navbar-left"><h1><%= link_to "Crazy Cocktails", cocktails_path %></h1></div>
    <div class="navbar-right d-flex">
        <div class="search-navbar">
            <%= form_tag cocktails_path, method: :get, class: "form_inline" do %>
            <%= text_field_tag :query, "", placeholder: "Search...", class:"search-navbar-input" %>
            <button class='btn-navbar-search ml-1' id="search-cocktails" style='width:40px;'>
                <%= icon_search("search") %>
            </button>
            <% end %>
        </div>
        <%= link_to "Add a new cocktail", new_cocktail_path, class: "btn btn-dark ml-2" %>
    </div>
</div>